In [2]:
import pandas
import pickle
import datetime

In [3]:
with open("data.p",'rb') as f:
    data = pickle.load(f)

In [4]:
data

,time,name,id,pairName,pairID,candidate_class
0,2021/3/4 18:03:54,李珺如,1830025057,(空),(空),秋江夜泊 周一 18:10-19:10┋归去来辞 周二 19:30-20:30┋春晓吟 周四...
1,2021/3/4 18:08:07,王亦淳,2030000068,(空),(空),凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30┋子夜吴歌 周四 ...
2,2021/3/4 18:09:13,林希,2,(空),(空),凤求凰 周二 18:10-19:10┋子夜吴歌 周四 19:30-20:30
3,2021/3/4 18:10:04,赵桐,1930031237,(空),(空),凤求凰 周二 18:10-19:10
4,2021/3/4 18:10:14,李静蕾,2030006085,(空),(空),凤求凰 周二 18:10-19:10
...,...,...,...,...,...,...
80,2021/3/4 21:22:39,谢尚苡,1730001095,(空),(空),仙翁操 周三 18:10-19:10
81,2021/3/4 21:31:33,柳万丝,1730006106,(空),(空),春晓吟 周四 18:10-19:10
82,2021/3/4 21:45:29,蔡月晴,1930006008,(空),(空),太古引 周一 19:30-20:30┋凤求凰 周二 18:10-19:10┋子夜吴歌 周四 ...
83,2021/3/4 21:47:39,彭爽,2030223158,(空),(空),凤求凰 周二 18:10-19:10
84,2021/3/4 23:11:39,葛润华,2030006054,(空),(空),子夜吴歌 周四 19:30-20:30

In [109]:
tempFrame = data.loc[(data["pairName"] != "(空)") & (data["pairID"] != "(空)")].reset_index(drop=True)
tempFrame

,time,name,id,pairName,pairID,candidate_class
0,2021/3/4 18:13:06,周婉然,1930006277,李文睿,1930025045,凤求凰 周二 18:10-19:10
1,2021/3/4 18:13:08,李文睿,19,周婉然,1930009277,凤求凰 周二 18:10-19:10
2,2021/3/4 18:13:52,刘熠阳,1930031113,蒋怡帆,1930016018,子夜吴歌 周四 19:30-20:30
3,2021/3/4 18:16:03,郑亦楠,2030006265,魏熙琳,2030001097,子夜吴歌 周四 19:30-20:30
4,2021/3/4 18:16:07,魏熙琳,2030001097,郑亦楠,2030006265,子夜吴歌 周四 19:30-20:30
5,2021/3/4 18:16:23,蒋怡帆,1930016018,刘熠阳,1930031113,子夜吴歌 周四 19:30-20:30
6,2021/3/4 18:16:43,普灵翎,1930024196,栾凯琪,1930031121,子夜吴歌 周四 19:30-20:30
7,2021/3/4 18:16:43,栾凯琪,1930031121,普灵翎,1930024196,子夜吴歌 周四 19:30-20:30
8,2021/3/4 18:20:22,高明月,2030024065,曾骏依,2030016063,凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30
9,2021/3/4 18:20:24,曾骏依,2030016063,高明月,2030024065,凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30
10,2021/3/4 18:21:02,张笑言,1930025123,周笛尔,1930025132,太古引 周一 19:30-20:30
11,2021/3/4 18:21:24,周笛尔,1930025132,张笑言,1930025123,太古引 周一 19:30-20:30
12,2021/3/4 18:29:58,余晓桐,1930005060,孔德然,1930026061,太古引 周一 19:30-20:30
13,2021/3/4 18:36:42,石婉彤,20,郑亦楠,2030006256,子夜吴歌 周四 19:30-20:30
14,2021/3/4 18:37:54,陈倚慧,1930001009,陈杨彤,1930001007,子夜吴歌 周四 19:30-20:30
15,2021/3/4 20:42:44,王淳羚,1930031165,王淳羚,1930031165,太古引 周一 19:30-20:30┋凤求凰 周二 18:10-19:10
16,2021/3/4 20:57:28,陈杨彤,1930001007,陈倚慧,1930001009,子夜吴歌 周四 19:30-20:30

In [52]:
tempFrame.iloc[0,2]

'1930006277'

In [98]:
strip_list = []
for i in range(tempFrame.shape[0]):
    name = tempFrame["name"][i]
    id = tempFrame["id"][i]
    pair_name = tempFrame["pairName"][i]
    pair_id = tempFrame["pairID"][i]
    name_boolean = (tempFrame["name"] == pair_name)
    id_boolean = (tempFrame["id"] == pair_id)
    if (True in list(name_boolean)) and (True in list(id_boolean)) and (id_boolean == name_boolean).all():
        if (tempFrame.loc[name_boolean,["pairName"]].iloc[0,0] == name) and (tempFrame.loc[name_boolean,["pairID"]].iloc[0,0] == id):
            pass
        else:
            strip_list.append(i)
    else:
        strip_list.append(i)
    if (name == pair_name) and (id == pair_id):
        strip_list.append(i)

In [114]:
strip_list = []
for i in range(tempFrame.shape[0]):
    id = tempFrame["id"][i]
    pair_id = tempFrame["pairID"][i]
    id_boolean = (tempFrame["id"] == pair_id)
    if (True in list(id_boolean)):
        if (tempFrame.loc[id_boolean,["pairID"]].iloc[0,0] == id):
            pass
        else:
            strip_list.append(i)
    else:
        strip_list.append(i)
    if (id == pair_id):
        strip_list.append(i)

In [91]:
strip_list = []
for i in range(tempFrame.shape[0]):
    name = tempFrame["name"][i]
    pair_name = tempFrame["pairName"][i]
    name_boolean = (tempFrame["name"] == pair_name)
    if (True in list(name_boolean)):
        if (tempFrame.loc[name_boolean,["pairName"]].iloc[0,0] == name):
            pass
        else:
            strip_list.append(i)
    else:
        strip_list.append(i)
    if (name == pair_name):
        strip_list.append(i)

In [115]:
strip_list

[0, 1, 12, 13, 15]

In [116]:
tempFrame.drop(strip_list,inplace=True)

In [117]:
tempFrame = tempFrame.reset_index(drop=True)
tempFrame

,time,name,id,pairName,pairID,candidate_class
0,2021/3/4 18:13:52,刘熠阳,1930031113,蒋怡帆,1930016018,子夜吴歌 周四 19:30-20:30
1,2021/3/4 18:16:03,郑亦楠,2030006265,魏熙琳,2030001097,子夜吴歌 周四 19:30-20:30
2,2021/3/4 18:16:07,魏熙琳,2030001097,郑亦楠,2030006265,子夜吴歌 周四 19:30-20:30
3,2021/3/4 18:16:23,蒋怡帆,1930016018,刘熠阳,1930031113,子夜吴歌 周四 19:30-20:30
4,2021/3/4 18:16:43,普灵翎,1930024196,栾凯琪,1930031121,子夜吴歌 周四 19:30-20:30
5,2021/3/4 18:16:43,栾凯琪,1930031121,普灵翎,1930024196,子夜吴歌 周四 19:30-20:30
6,2021/3/4 18:20:22,高明月,2030024065,曾骏依,2030016063,凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30
7,2021/3/4 18:20:24,曾骏依,2030016063,高明月,2030024065,凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30
8,2021/3/4 18:21:02,张笑言,1930025123,周笛尔,1930025132,太古引 周一 19:30-20:30
9,2021/3/4 18:21:24,周笛尔,1930025132,张笑言,1930025123,太古引 周一 19:30-20:30
10,2021/3/4 18:37:54,陈倚慧,1930001009,陈杨彤,1930001007,子夜吴歌 周四 19:30-20:30
11,2021/3/4 20:57:28,陈杨彤,1930001007,陈倚慧,1930001009,子夜吴歌 周四 19:30-20:30

In [66]:
pair_name1 = []
pair_id1 = []
pair_name2 = []
pair_id2 = []
pair_candidate_class = []
pair_finish_time = []

In [67]:
for i in tempFrame.shape[0]:
    name = tempFrame["name"][i]
    id = tempFrame["id"][i]
    pair_name = tempFrame["pairName"][i]
    pair_id = tempFrame["pairID"][i]
    if (name not in pair_name2) and (id not in pair_id2) and (pairName not in pair_name1) and (pairID not in pair_id1)

(True, True, True)

In [68]:
pandas.DataFrame({"name":name_boolean,"id":id_boolean})

     name     id
0   False  False
1   False  False
2   False  False
3   False  False
4   False  False
5   False  False
6   False  False
7   False  False
8   False  False
9   False  False
10  False  False
11  False  False
12  False  False
13  False  False
14  False  False
15  False  False
16  False  False

In [72]:
name_boolean

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
Name: name, dtype: bool

In [74]:
2 in name_boolean

True

In [80]:
3 in pandas.Series([1, 2])

False

In [79]:
list(pandas.Series([False, False]))

[False, False]

In [84]:
a = [1,2]+1

TypeError: can only concatenate list (not "int") to list

In [96]:
dt = datetime.datetime.strptime('2021/3/4 18:13:06','%Y/%m/%d %H:%M:%S')
dt

datetime.datetime(2021, 3, 4, 18, 13, 6)

In [4]:
data

,time,name,id,pairName,pairID,candidate_class
0,2021/3/4 18:03:54,李珺如,1830025057,(空),(空),秋江夜泊 周一 18:10-19:10┋归去来辞 周二 19:30-20:30┋春晓吟 周四...
1,2021/3/4 18:08:07,王亦淳,2030000068,(空),(空),凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30┋子夜吴歌 周四 ...
2,2021/3/4 18:09:13,林希,2,(空),(空),凤求凰 周二 18:10-19:10┋子夜吴歌 周四 19:30-20:30
3,2021/3/4 18:10:04,赵桐,1930031237,(空),(空),凤求凰 周二 18:10-19:10
4,2021/3/4 18:10:14,李静蕾,2030006085,(空),(空),凤求凰 周二 18:10-19:10
...,...,...,...,...,...,...
80,2021/3/4 21:22:39,谢尚苡,1730001095,(空),(空),仙翁操 周三 18:10-19:10
81,2021/3/4 21:31:33,柳万丝,1730006106,(空),(空),春晓吟 周四 18:10-19:10
82,2021/3/4 21:45:29,蔡月晴,1930006008,(空),(空),太古引 周一 19:30-20:30┋凤求凰 周二 18:10-19:10┋子夜吴歌 周四 ...
83,2021/3/4 21:47:39,彭爽,2030223158,(空),(空),凤求凰 周二 18:10-19:10
84,2021/3/4 23:11:39,葛润华,2030006054,(空),(空),子夜吴歌 周四 19:30-20:30

In [5]:
data.loc[0]

time                                               2021/3/4 18:03:54
name                                                             李珺如
id                                                        1830025057
pairName                                                         (空)
pairID                                                           (空)
candidate_class    秋江夜泊 周一 18:10-19:10┋归去来辞 周二 19:30-20:30┋春晓吟 周四...
Name: 0, dtype: object

In [6]:
a = data.drop(0)

In [7]:
a

,time,name,id,pairName,pairID,candidate_class
1,2021/3/4 18:08:07,王亦淳,2030000068,(空),(空),凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30┋子夜吴歌 周四 ...
2,2021/3/4 18:09:13,林希,2,(空),(空),凤求凰 周二 18:10-19:10┋子夜吴歌 周四 19:30-20:30
3,2021/3/4 18:10:04,赵桐,1930031237,(空),(空),凤求凰 周二 18:10-19:10
4,2021/3/4 18:10:14,李静蕾,2030006085,(空),(空),凤求凰 周二 18:10-19:10
5,2021/3/4 18:10:17,毕然,2030025001,(空),(空),湘江怨 周三 19:30-20:30
...,...,...,...,...,...,...
80,2021/3/4 21:22:39,谢尚苡,1730001095,(空),(空),仙翁操 周三 18:10-19:10
81,2021/3/4 21:31:33,柳万丝,1730006106,(空),(空),春晓吟 周四 18:10-19:10
82,2021/3/4 21:45:29,蔡月晴,1930006008,(空),(空),太古引 周一 19:30-20:30┋凤求凰 周二 18:10-19:10┋子夜吴歌 周四 ...
83,2021/3/4 21:47:39,彭爽,2030223158,(空),(空),凤求凰 周二 18:10-19:10
84,2021/3/4 23:11:39,葛润华,2030006054,(空),(空),子夜吴歌 周四 19:30-20:30

In [10]:
a.iloc[0]

time                                               2021/3/4 18:08:07
name                                                             王亦淳
id                                                        2030000068
pairName                                                         (空)
pairID                                                           (空)
candidate_class    凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30┋子夜吴歌 周四 ...
Name: 1, dtype: object

In [12]:
type(data.iloc[0]["name"])

str

In [13]:
x = [(1,2,3),(3,2,1),(1,3,4),(1,2,4),(3,5,7),(6,6,6)]
print(sorted(x,key=lambda x:(x[1],x[2])))

[(3, 2, 1), (1, 2, 3), (1, 2, 4), (1, 3, 4), (3, 5, 7), (6, 6, 6)]

In [15]:
import time
time1 = time.mktime(time.strptime("2020/01/03 22:33:40",'%Y/%m/%d %H:%M:%S'))

In [16]:
time2 = time.mktime(time.strptime("2020/01/03 22:34:40",'%Y/%m/%d %H:%M:%S'))

In [17]:
time1, time2

(1578062020.0, 1578062080.0)

In [18]:
time1<time2

True

In [19]:
a = set([1,2,3])
b = set([2,3])

a&b

{2, 3}

In [20]:
data

,time,name,id,pairName,pairID,candidate_class
0,2021/3/4 18:03:54,李珺如,1830025057,(空),(空),秋江夜泊 周一 18:10-19:10┋归去来辞 周二 19:30-20:30┋春晓吟 周四...
1,2021/3/4 18:08:07,王亦淳,2030000068,(空),(空),凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30┋子夜吴歌 周四 ...
2,2021/3/4 18:09:13,林希,2,(空),(空),凤求凰 周二 18:10-19:10┋子夜吴歌 周四 19:30-20:30
3,2021/3/4 18:10:04,赵桐,1930031237,(空),(空),凤求凰 周二 18:10-19:10
4,2021/3/4 18:10:14,李静蕾,2030006085,(空),(空),凤求凰 周二 18:10-19:10
...,...,...,...,...,...,...
80,2021/3/4 21:22:39,谢尚苡,1730001095,(空),(空),仙翁操 周三 18:10-19:10
81,2021/3/4 21:31:33,柳万丝,1730006106,(空),(空),春晓吟 周四 18:10-19:10
82,2021/3/4 21:45:29,蔡月晴,1930006008,(空),(空),太古引 周一 19:30-20:30┋凤求凰 周二 18:10-19:10┋子夜吴歌 周四 ...
83,2021/3/4 21:47:39,彭爽,2030223158,(空),(空),凤求凰 周二 18:10-19:10
84,2021/3/4 23:11:39,葛润华,2030006054,(空),(空),子夜吴歌 周四 19:30-20:30

In [22]:
int(data["id"][0])

1830025057

In [23]:
pair = data.loc[data["name"] == "王亦淳"]

In [28]:
type(pair["name"])

pandas.core.series.Series

In [29]:
with open("data2.p",'rb') as f:
    data2 = pickle.load(f)
    
data2

,index,time,name,id,pairName,pairID,candidate_class
0,1,2021/3/4 18:03:54,李珺如,1830025057,(空),(空),秋江夜泊 周一 18:10-19:10┋归去来辞 周二 19:30-20:30┋春晓吟 周四...
1,2,2021/3/4 18:08:07,王亦淳,2030000068,(空),(空),凤求凰 周二 18:10-19:10┋湘江怨 周三 19:30-20:30┋子夜吴歌 周四 ...
2,3,2021/3/4 18:09:13,林希,2,(空),(空),凤求凰 周二 18:10-19:10┋子夜吴歌 周四 19:30-20:30
3,4,2021/3/4 18:10:04,赵桐,1930031237,(空),(空),凤求凰 周二 18:10-19:10
4,5,2021/3/4 18:10:14,李静蕾,2030006085,(空),(空),凤求凰 周二 18:10-19:10
...,...,...,...,...,...,...,...
80,81,2021/3/4 21:22:39,谢尚苡,1730001095,(空),(空),仙翁操 周三 18:10-19:10
81,82,2021/3/4 21:31:33,柳万丝,1730006106,(空),(空),春晓吟 周四 18:10-19:10
82,83,2021/3/4 21:45:29,蔡月晴,1930006008,(空),(空),太古引 周一 19:30-20:30┋凤求凰 周二 18:10-19:10┋子夜吴歌 周四 ...
83,84,2021/3/4 21:47:39,彭爽,2030223158,(空),(空),凤求凰 周二 18:10-19:10
84,85,2021/3/4 23:11:39,葛润华,2030006054,(空),(空),子夜吴歌 周四 19:30-20:30

In [37]:
data2.loc[data2["index"] == 5]["index"].iloc[0]

5

In [33]:
data2["index"]

0      1
1      2
2      3
3      4
4      5
      ..
80    81
81    82
82    83
83    84
84    85
Name: index, Length: 85, dtype: int64